---
version: "3.3"

services:
  web:
    image: {{ cookiecutter.docker_image }}
    ports:
      - "8080:8080"
    command: gunicorn -b 0.0.0.0:8080 --access-logfile - -w 1 {{ cookiecutter.app_module }}:app
    deploy:
      replicas: 3
    secrets:
      - secret_key
    environment:
      SECRET_KEY_FILE: /run/secrets/secret_key

secrets:
  secret_key:
    file: ./etc/dev-flask-secret-key
